#!/bin/bash
BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

cd  src
pipenv run pylint $(find -name "*.py")
PYTHONPATH=${BASEDIR}/src pipenv run py.test -s -v ${BASEDIR}/tests 
