#!/bin/bash
BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

pipenv run pylint $(find src -name "*.py")

cd src
PYTHONPATH=${BASEDIR}/src pipenv run py.test -s -v ${BASEDIR}/tests 
